function [plat, lidar] = createLidar(plat, updateRate, maxRange, azimuthResolution, elevationResolution, elevationLimits)
    % createLidar - ...
    %
    %   [scene, roi] = createTarget(scene, xbounds, ybounds, zlimits, size, updateRate, simTime)
    %
    % Inputs:
    %   - plat: ...
    %   - updateRate: ...
    %   - zlimits: ...
    %   - maxRange: ...
    %
    % Outputs:
    %   - plat: ...
    %   - lidar: ...

    lidarModel = uavLidarPointCloudGenerator("UpdateRate",updateRate,"MaxRange",maxRange,"AzimuthResolution",azimuthResolution,"ElevationLimits",elevationLimits,"ElevationResolution",elevationResolution,"HasOrganizedOutput",true);
    lidar = uavSensor("Lidar",plat,lidarModel,MountingLocation=[0,0,-1]);
end
