function scene = createScene(xlimits, ylimits, zlimits, updateRate, simTime)
    % createScene - ...
    %
    %   scene = createScene(xlimits, ylimits, zlimits, updateRate, simTime)
    %
    % Inputs:
    %   - xlimits: ...
    %   - ylimits: ...
    %   - zlimits: ...
    %   - updateRate: ...
    %   - simTime: ...
    %
    % Outputs:
    %   - scene: UAV scenario object.

    vertices = [xlimits(1) ylimits(1); xlimits(2) ylimits(1); xlimits(2) ylimits(2); xlimits(1) ylimits(2)];
    scene = uavScenario("UpdateRate",updateRate,"StopTime",simTime,"HistoryBufferSize",200);
    addMesh(scene,"polygon",{vertices,zlimits},0.651*ones(1,3));
end
